# Loki Configuration
# Log aggregation system for LICS

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

# Limits configuration
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 1 week
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_streams_per_user: 10000
  max_line_size: 256000

  # Per stream rate limits
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB

  # Query limits
  max_entries_limit_per_query: 5000
  max_concurrent_tail_requests: 10
  max_cache_freshness_per_query: '10m'

# Chunk store configuration
chunk_store_config: {}

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h  # 2 weeks

compactor:
  working_directory: /loki/compactor

# Analytics
analytics:
  reporting_enabled: false